### **Proyecto 2 - Algoritmo MTF (Move to Front)**
Universidad del Valle de Guatemala

Análisis y Diseño de Algoritmos

Luis Pedro Cuéllar - 18220

In [1]:
import numpy as np

In [2]:
def MTF(req_list, config_list):
  old_list = config_list
  new_list = config_list
  total_cost = 0

  for i in req_list:
    cost = 0
    old_list = new_list

    for j in old_list:
      cost += 1

      if i == j:
        nth_position = np.where(old_list == i)

        new_list = np.delete(new_list, nth_position)
        new_list = np.insert(new_list, 0, i)

        print(old_list, i, cost, new_list)
        
        break

    total_cost += cost

  print("\nCOSTO TOTAL = %d \n" % (total_cost))   

###**a)**



*   **Lista de Configuarción = [0, 1, 2, 3, 4]**
*   **Secuencia de Solicitudes = [0, 1, 2, 3, 4,0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]**

In [3]:
config_list = np.array([0, 1, 2, 3, 4])
req_list = np.array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

print("CANTIDAD DE SOLICITUDES -> %d\n" %(len(req_list)))
MTF(req_list, config_list)

CANTIDAD DE SOLICITUDES -> 20

[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 1 2 [1 0 2 3 4]
[1 0 2 3 4] 2 3 [2 1 0 3 4]
[2 1 0 3 4] 3 4 [3 2 1 0 4]
[3 2 1 0 4] 4 5 [4 3 2 1 0]
[4 3 2 1 0] 0 5 [0 4 3 2 1]
[0 4 3 2 1] 1 5 [1 0 4 3 2]
[1 0 4 3 2] 2 5 [2 1 0 4 3]
[2 1 0 4 3] 3 5 [3 2 1 0 4]
[3 2 1 0 4] 4 5 [4 3 2 1 0]
[4 3 2 1 0] 0 5 [0 4 3 2 1]
[0 4 3 2 1] 1 5 [1 0 4 3 2]
[1 0 4 3 2] 2 5 [2 1 0 4 3]
[2 1 0 4 3] 3 5 [3 2 1 0 4]
[3 2 1 0 4] 4 5 [4 3 2 1 0]
[4 3 2 1 0] 0 5 [0 4 3 2 1]
[0 4 3 2 1] 1 5 [1 0 4 3 2]
[1 0 4 3 2] 2 5 [2 1 0 4 3]
[2 1 0 4 3] 3 5 [3 2 1 0 4]
[3 2 1 0 4] 4 5 [4 3 2 1 0]

COSTO TOTAL = 90 



### **b)** 

*   **Lista de Configuarción = [0, 1, 2, 3, 4]**
*   **Secuencia de Solicitudes = [4, 3, 2, 1, 0, 1, 2, 3, 4, 3, 2, 1, 0, 1, 2, 3, 4]**

In [4]:
config_list = np.array([0, 1, 2, 3, 4])
req_list = np.array([4, 3, 2, 1, 0, 1, 2, 3, 4, 3, 2, 1, 0, 1, 2, 3, 4])

print("CANTIDAD DE SOLICITUDES -> %d\n" %(len(req_list)))
MTF(req_list, config_list)

CANTIDAD DE SOLICITUDES -> 17

[0 1 2 3 4] 4 5 [4 0 1 2 3]
[4 0 1 2 3] 3 5 [3 4 0 1 2]
[3 4 0 1 2] 2 5 [2 3 4 0 1]
[2 3 4 0 1] 1 5 [1 2 3 4 0]
[1 2 3 4 0] 0 5 [0 1 2 3 4]
[0 1 2 3 4] 1 2 [1 0 2 3 4]
[1 0 2 3 4] 2 3 [2 1 0 3 4]
[2 1 0 3 4] 3 4 [3 2 1 0 4]
[3 2 1 0 4] 4 5 [4 3 2 1 0]
[4 3 2 1 0] 3 2 [3 4 2 1 0]
[3 4 2 1 0] 2 3 [2 3 4 1 0]
[2 3 4 1 0] 1 4 [1 2 3 4 0]
[1 2 3 4 0] 0 5 [0 1 2 3 4]
[0 1 2 3 4] 1 2 [1 0 2 3 4]
[1 0 2 3 4] 2 3 [2 1 0 3 4]
[2 1 0 3 4] 3 4 [3 2 1 0 4]
[3 2 1 0 4] 4 5 [4 3 2 1 0]

COSTO TOTAL = 67 



### **c)**



*   **¿Para  qué  secuencia  de 20 solicitudes se  obtiene  el  mínimo  costo total  de  acceso  utilizando  el algoritmo MTF para la configuración 0, 1, 2, 3, 4? ¿Cuál sería ese costo total de acceso?**

In [5]:
config_list = np.array([0, 1, 2, 3, 4])
req_list = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

print("CANTIDAD DE SOLICITUDES -> %d\n" %(len(req_list)))
MTF(req_list, config_list)

CANTIDAD DE SOLICITUDES -> 20

[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]

COSTO TOTAL = 20 



### **d)**



*   **¿Para qué secuencia de 20 solicitudes se obtiene el peor de los casos utilizando el algoritmo MTF para la configuración 0, 1, 2, 3, 4? ¿Cuál sería ese costo total de acceso?**


In [6]:
config_list = np.array([0, 1, 2, 3, 4])
req_list = np.array([4, 3, 2, 1, 0, 4, 3, 2, 1, 0, 4, 3, 2, 1, 0, 4, 3, 2, 1, 0])

print("CANTIDAD DE SOLICITUDES -> %d\n" %(len(req_list)))
MTF(req_list, config_list)

CANTIDAD DE SOLICITUDES -> 20

[0 1 2 3 4] 4 5 [4 0 1 2 3]
[4 0 1 2 3] 3 5 [3 4 0 1 2]
[3 4 0 1 2] 2 5 [2 3 4 0 1]
[2 3 4 0 1] 1 5 [1 2 3 4 0]
[1 2 3 4 0] 0 5 [0 1 2 3 4]
[0 1 2 3 4] 4 5 [4 0 1 2 3]
[4 0 1 2 3] 3 5 [3 4 0 1 2]
[3 4 0 1 2] 2 5 [2 3 4 0 1]
[2 3 4 0 1] 1 5 [1 2 3 4 0]
[1 2 3 4 0] 0 5 [0 1 2 3 4]
[0 1 2 3 4] 4 5 [4 0 1 2 3]
[4 0 1 2 3] 3 5 [3 4 0 1 2]
[3 4 0 1 2] 2 5 [2 3 4 0 1]
[2 3 4 0 1] 1 5 [1 2 3 4 0]
[1 2 3 4 0] 0 5 [0 1 2 3 4]
[0 1 2 3 4] 4 5 [4 0 1 2 3]
[4 0 1 2 3] 3 5 [3 4 0 1 2]
[3 4 0 1 2] 2 5 [2 3 4 0 1]
[2 3 4 0 1] 1 5 [1 2 3 4 0]
[1 2 3 4 0] 0 5 [0 1 2 3 4]

COSTO TOTAL = 100 



### **e)**


> 1.


> > *   **Lista de Configuración = [0, 1, 2, 3, 4]**


> > *   **Sequencia de Solicitudes = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]**

In [7]:
config_list = np.array([0, 1, 2, 3, 4])
req_list = np.array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

print("CANTIDAD DE SOLICITUDES -> %d\n" %(len(req_list)))
MTF(req_list, config_list)

CANTIDAD DE SOLICITUDES -> 20

[0 1 2 3 4] 2 3 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]

COSTO TOTAL = 22 



> 2.


> > *   **Lista de Configuración = [0, 1, 2, 3, 4]**


> > *   **Sequencia de Solicitudes = [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,3, 3, 3, 3]**

In [8]:
config_list = np.array([0, 1, 2, 3, 4])
req_list = np.array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,3, 3, 3, 3])

print("CANTIDAD DE SOLICITUDES -> %d\n" %(len(req_list)))
MTF(req_list, config_list)

CANTIDAD DE SOLICITUDES -> 20

[0 1 2 3 4] 3 4 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]

COSTO TOTAL = 23 





> 3.   **¿Cuál sería  la  fórmula  para  calcular  el  costo  de 𝑛 solicitudes del mismo elemento si éste  se encuentra inicialmente en la 𝑘-ésma posición de la lista de configuración?**



> > La formula sería:
> > >  *n* + *k* - 1







### **f)**

In [9]:
def IMTF(req_list, config_list):
  old_list = config_list
  new_list = config_list
  total_cost = 0
  count = 0

  for i in req_list:
    cost = 0
    old_list = new_list

    for j in old_list:
      cost += 1

      if i == j:
        nth_position = np.where(old_list == i)[0][0]

        if (nth_position == 0):
          print(old_list, i, cost, new_list)

        else:
          for k in range(1, nth_position + 1):
            if (count + k <= len(req_list) - 1):
              if (i == req_list[count + k]):
                new_list = np.delete(new_list, nth_position)
                new_list = np.insert(new_list, 0, i)

                print(old_list, i, cost, new_list)
                
                break
              
              else:
                if (k == nth_position):
                  print(old_list, i, cost, new_list)

            else:
              print(old_list, i, cost, new_list)
              
              break

        count += 1
        total_cost += cost
  
        break        
  
  print("\nCOSTO TOTAL = %d \n" % (total_cost))   



> **1.**


> *   **Lista de Configuarción = [0, 1, 2, 3, 4]**
> *   **Secuencia de Solicitudes = [0, 1, 2, 3, 4,0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]** **bold text**





In [10]:
config_list = np.array([0, 1, 2, 3, 4])
req_list = np.array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

print("CANTIDAD DE SOLICITUDES -> %d\n" %(len(req_list)))
IMTF(req_list, config_list)

CANTIDAD DE SOLICITUDES -> 20

[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 1 2 [0 1 2 3 4]
[0 1 2 3 4] 2 3 [0 1 2 3 4]
[0 1 2 3 4] 3 4 [0 1 2 3 4]
[0 1 2 3 4] 4 5 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 1 2 [0 1 2 3 4]
[0 1 2 3 4] 2 3 [0 1 2 3 4]
[0 1 2 3 4] 3 4 [0 1 2 3 4]
[0 1 2 3 4] 4 5 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 1 2 [0 1 2 3 4]
[0 1 2 3 4] 2 3 [0 1 2 3 4]
[0 1 2 3 4] 3 4 [0 1 2 3 4]
[0 1 2 3 4] 4 5 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 1 2 [0 1 2 3 4]
[0 1 2 3 4] 2 3 [0 1 2 3 4]
[0 1 2 3 4] 3 4 [0 1 2 3 4]
[0 1 2 3 4] 4 5 [0 1 2 3 4]

COSTO TOTAL = 60 





> **2.**


> *   **Lista de Configuarción = [0, 1, 2, 3, 4]**
> *   **Secuencia de Solicitudes = [4, 3, 2, 1, 0, 1, 2, 3, 4, 3, 2, 1, 0, 1, 2, 3, 4]**









In [11]:
config_list = np.array([0, 1, 2, 3, 4])
req_list = np.array([4, 3, 2, 1, 0, 1, 2, 3, 4, 3, 2, 1, 0, 1, 2, 3, 4])

print("CANTIDAD DE SOLICITUDES -> %d\n" %(len(req_list)))
IMTF(req_list, config_list)

CANTIDAD DE SOLICITUDES -> 17

[0 1 2 3 4] 4 5 [0 1 2 3 4]
[0 1 2 3 4] 3 4 [0 1 2 3 4]
[0 1 2 3 4] 2 3 [0 1 2 3 4]
[0 1 2 3 4] 1 2 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 1 2 [0 1 2 3 4]
[0 1 2 3 4] 2 3 [0 1 2 3 4]
[0 1 2 3 4] 3 4 [3 0 1 2 4]
[3 0 1 2 4] 4 5 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 2 4 [3 0 1 2 4]
[3 0 1 2 4] 1 3 [1 3 0 2 4]
[1 3 0 2 4] 0 3 [1 3 0 2 4]
[1 3 0 2 4] 1 1 [1 3 0 2 4]
[1 3 0 2 4] 2 4 [1 3 0 2 4]
[1 3 0 2 4] 3 2 [1 3 0 2 4]
[1 3 0 2 4] 4 5 [1 3 0 2 4]

COSTO TOTAL = 52 



> **3.**



> *   **¿Para  qué  secuencia  de 20 solicitudes se  obtiene  el  mínimo  costo total  de  acceso  utilizando  el algoritmo IMTF para la configuración 0, 1, 2, 3, 4? ¿Cuál sería ese costo total de acceso?**

In [12]:
config_list = np.array([0, 1, 2, 3, 4])
req_list = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

print("CANTIDAD DE SOLICITUDES -> %d\n" %(len(req_list)))
IMTF(req_list, config_list)

CANTIDAD DE SOLICITUDES -> 20

[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]
[0 1 2 3 4] 0 1 [0 1 2 3 4]

COSTO TOTAL = 20 



> **4.**
> *   **¿Para qué secuencia de 20 solicitudes se obtiene el peor de los casos utilizando el algoritmo IMTF para la configuración 0, 1, 2, 3, 4? ¿Cuál sería ese costo total de acceso?**

In [13]:
config_list = np.array([0, 1, 2, 3, 4])
req_list = np.array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

print("CANTIDAD DE SOLICITUDES -> %d\n" %(len(req_list)))
IMTF(req_list, config_list)

CANTIDAD DE SOLICITUDES -> 20

[0 1 2 3 4] 4 5 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]
[4 0 1 2 3] 4 1 [4 0 1 2 3]

COSTO TOTAL = 24 





> **5.**





> > **5.1.**


> > *   **Lista de Configuración = [0, 1, 2, 3, 4]**


> > *   **Sequencia de Solicitudes = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]**





In [14]:
config_list = np.array([0, 1, 2, 3, 4])
req_list = np.array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

print("CANTIDAD DE SOLICITUDES -> %d\n" %(len(req_list)))
IMTF(req_list, config_list)

CANTIDAD DE SOLICITUDES -> 20

[0 1 2 3 4] 2 3 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]
[2 0 1 3 4] 2 1 [2 0 1 3 4]

COSTO TOTAL = 22 



> > **5.2.**


> > *   **Lista de Configuración = [0, 1, 2, 3, 4]**


> > *   **Sequencia de Solicitudes = [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,3, 3, 3, 3]**



In [15]:
config_list = np.array([0, 1, 2, 3, 4])
req_list = np.array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,3, 3, 3, 3])

print("CANTIDAD DE SOLICITUDES -> %d\n" %(len(req_list)))
IMTF(req_list, config_list)

CANTIDAD DE SOLICITUDES -> 20

[0 1 2 3 4] 3 4 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]
[3 0 1 2 4] 3 1 [3 0 1 2 4]

COSTO TOTAL = 23 

